#!/bin/bash
lsblk
growpart /dev/nvme0n1 4
lvextend -L +30G /dev/mapper/RootVG-varVol
xfs_growfs /var
dnf -y install dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
systemctl start docker
systemctl enable docker
usermod -aG docker ec2-user

#if this doesnot work use the below script almost both are same


#!/bin/bash

set -e

# Install growpart
dnf -y install cloud-utils-growpart

# Disk check
lsblk

# Extend partition
growpart /dev/nvme0n1 4

# Extend LVM
lvextend -L +30G /dev/mapper/RootVG-varVol

# Resize filesystem
xfs_growfs /var

# Install Docker
dnf -y install dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Start Docker
systemctl enable docker
systemctl start docker

# Add user to docker group
usermod -aG docker ec2-user