# we need mongodb version 7 so using official mongo 7.0 version image
# docker-entrypoint-initdb.d is the dir to initialise the database for the first time on db startup
FROM mongo:7.0
COPY *.js /docker-entrypoint-initdb.d
